archive = "bionic"
version = "18.04"
origin = "system76"
label = "System76"
email = "info@system76.com"
extra_repos = [ "deb http://ppa.launchpad.net/system76/pop/ubuntu bionic main" ]

[[direct]]
name = "code"
version = "1.33.1-1554971066"

    [[direct.urls]]
    url = "https://az764295.vo.msecnd.net/stable/51b0b28134d51361cf996d2f0a1c698247aeabd8/code_1.33.1-1554971066_amd64.deb"
    checksum = "b46165fb8cb2046afff69475d9dc398897de5921cf6c8c682fbc41a6d693aded"

[[direct]]
name = "discord"
version = "0.0.9"

    [[direct.urls]]
    url = "https://dl.discordapp.net/apps/linux/0.0.9/discord-0.0.9.deb"
    checksum = "2a5f0f0e940d2d2dbb9a789baab1a58a54e7dacc598d628b2667b5244df84bbf"

[[direct]]
name = "slack-desktop"
version = "3.3.8"

    [[direct.urls]]
    url = "https://downloads.slack-edge.com/linux_releases/${name}-${version}-amd64.deb"
    checksum = "37042b2172edf1af02cbe48660800c355e0b16f8f8f5d1257525657ff72f8308"

[[direct]]
name = "spotify-client"
version = "1.1.0.237.g378f6f25-11"

    [[direct.urls]]
    url = "http://repository.spotify.com/pool/non-free/s/${name}/${name}_${version}_amd64.deb"
    checksum = "4b77c6baa59d5e8d8e6f800138fefdf579747cb81615b9711dfa25d6c2d5fa9f"

[[direct]]
name = "signal-desktop"
version = "1.23.1"

    [[direct.urls]]
    url = "https://updates.signal.org/desktop/apt/pool/main/s/${name}/${name}_${version}_amd64.deb"
    checksum = "9ad4f2eea627f6640fa72141f1a849077b73fceccdfb2e2a629cc163da051ac4"

[[direct]]
name = "google-chrome-stable"
version = "current"

    [[direct.urls]]
    url = "https://dl.google.com/linux/direct/${name}_${version}_amd64.deb"

[[direct]]
name = "gitkraken"
version = "current"

    [[direct.urls]]
    url = "https://release.gitkraken.com/linux/${name}-amd64.deb"
