archive = "bionic"
version = "18.04"
origin = "system76"
label = "System76"
email = "info@system76.com"
extra_repos = [ "deb http://ppa.launchpad.net/system76/pop/ubuntu bionic main" ]

[[direct]]
name = "slack-desktop"
version = "3.3.7"

    [[direct.urls]]
    url = "https://downloads.slack-edge.com/linux_releases/${name}-${version}-amd64.deb"
    checksum = "17310bc323eafcef86c134c7aea9b53a82f8394aa30a886ac419f9a5a23168e0"

[[direct]]
name = "spotify-client"
version = "1.1.0.237.g378f6f25-11"

    [[direct.urls]]
    url = "http://repository.spotify.com/pool/non-free/s/${name}/${name}_${version}_amd64.deb"
    checksum = "4b77c6baa59d5e8d8e6f800138fefdf579747cb81615b9711dfa25d6c2d5fa9f"

[[direct]]
name = "code"
version = "1.31.1-1549938243"

    [[direct.urls]]
    url = "https://az764295.vo.msecnd.net/stable/1b8e8302e405050205e69b59abb3559592bb9e60/code_1.31.1-1549938243_amd64.deb"
    checksum = "fb47deec394997fb6b9f06ed6d0c8417b163f82794a8dd90eb1aa8776b4009f9"

[[direct]]
name = "signal-desktop"
version = "1.22.0"

    [[direct.urls]]
    url = "https://updates.signal.org/desktop/apt/pool/main/s/${name}/${name}_${version}_amd64.deb"
    checksum = "c54fa57ca8e1f2c2a85869c8b8be357771d76dae6a737b5bb776d0b51d80b3c8"

[[direct]]
name = "google-chrome-stable"
version = "current"

    [[direct.urls]]
    url = "https://dl.google.com/linux/direct/${name}_${version}_amd64.deb"

[[direct]]
name = "steam"
version = "1.0.0.54+repack-5ubuntu1"

    [[direct.urls]]
    url = "http://us.archive.ubuntu.com/ubuntu/pool/multiverse/s/steam/${name}_${version}_i386.deb"
    checksum = "a3436f5dced446fb98f14db559017e55de6c3da12dd60cf5a33d689ea6c39a34"

    [[direct.urls]]
    name = "steam-installer"
    url = "http://us.archive.ubuntu.com/ubuntu/pool/multiverse/s/steam/${name}_${version}_all.deb"
    checksum = "907d60e8983dc49f2a33dfd092b36790f3320fe2102c4afddb0810ec042e75c0"

    [[direct.urls]]
    name = "steam-devices"
    url = "http://us.archive.ubuntu.com/ubuntu/pool/multiverse/s/steam/${name}_${version}_all.deb"
    checksum = "0c1aad76aaf0e4c6c9e4a151342be4d5499387e4e6597c3a9ea8878b3f787cba"

[[direct]]
name = "gitkraken"
version = "current"

    [[direct.urls]]
    url = "https://release.gitkraken.com/linux/${name}-amd64.deb"
