archive = "cosmic"
version = "18.04"
origin = "system76"
label = "System76"
email = "info@system76.com"
extra_repos = [ "deb http://ppa.launchpad.net/system76/pop/ubuntu cosmic main" ]

[[direct]]
name = "slack-desktop"
version = "3.3.8"

    [[direct.urls]]
    url = "https://downloads.slack-edge.com/linux_releases/${name}-${version}-amd64.deb"
    checksum = "37042b2172edf1af02cbe48660800c355e0b16f8f8f5d1257525657ff72f8308"

[[direct]]
name = "spotify-client"
version = "1.1.0.237.g378f6f25-11"

    [[direct.urls]]
    url = "http://repository.spotify.com/pool/non-free/s/${name}/${name}_${version}_amd64.deb"
    checksum = "4b77c6baa59d5e8d8e6f800138fefdf579747cb81615b9711dfa25d6c2d5fa9f"

[[direct]]
name = "code"
version = "1.32.3-1552606978"

    [[direct.urls]]
    url = "https://az764295.vo.msecnd.net/stable/a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4/code_1.32.3-1552606978_amd64.deb"
    checksum = "3347516c7c657598cf169b404472d5c669346db03c89293e02aeb462e696b4e0"

[[direct]]
name = "signal-desktop"
version = "1.23.1"

    [[direct.urls]]
    url = "https://updates.signal.org/desktop/apt/pool/main/s/${name}/${name}_${version}_amd64.deb"
    checksum = "9ad4f2eea627f6640fa72141f1a849077b73fceccdfb2e2a629cc163da051ac4"

[[direct]]
name = "google-chrome-stable"
version = "current"

    [[direct.urls]]
    url = "https://dl.google.com/linux/direct/${name}_${version}_amd64.deb"

[[direct]]
name = "gitkraken"
version = "current"

    [[direct.urls]]
    url = "https://release.gitkraken.com/linux/${name}-amd64.deb"
